### ISSUE TITLE
Missing YRA-30 - in SIs for Great Pumpkin Halloween Pursuit Race

### ISSUE THREAD

**Issue by davlee1972** [nkiesel/YRA-Marks#11]
RACING AREA & COURSE
7.1 The course for the race will be from the start near the
Southampton platform, around Angel Island & Alcatraz in
either direction, leaving both islands either to port or both
to starboard, and back to the finish line **near Red # 6
channel mark in the Richmond Channel.** Course length is
10.7 miles.

37.903908 | -122.420154 | YRA-29 | [5655] R '4' Fl R 4s Southampton Shoal Channel Lighted Buoy 4

**37.91624 | -122.42233 | YRA-30 | R '6' Fl R 2.5s Southampton Shoal Channel Lighted Buoy 6**

37.759207 | -122.363997 | YRA-31 | Temp YC buoy approx. 1.2 nm SE of Mission Rock Terminal

**Comment by nkiesel** [comment]
I can add this mark. Just wondering where you found that this mark is called YRA-30?

**Comment by nkiesel** [comment]
Actually, I think the mark from the SIs is "Red # 6 channel mark in the Richmond Channel" which called "RHC#6" in my list and not mark "Southampton Shoal Channel Lighted Buoy 6" which you called YRA-30 and is called "YRA-NR6" in my list. Thus, the only possible change to my list would be to rename "RHC#6" to "YRA-30" once you show me the source of that name (the http://yra.org/descriptionofmarks/ contains "NR6" but not "30").

**Comment by davlee1972** [comment]
It's from my GPX file on my GPS which I've been using for a decade..

![image](https://github.com/nkiesel/YRA-Marks/assets/24494353/bc26089f-6d93-4bbd-84e9-3d746a308eb7)

**Comment by davlee1972** [comment]
I guess it got renamed to NR6.

**Comment by davlee1972** [comment]
[yra_marks.zip](https://github.com/nkiesel/YRA-Marks/files/13196711/yra_marks.zip)

All my marks from Monterey to Petaluma..

**Comment by davlee1972** [comment]
I guess I'll figure it out tomorrow on the water.. This the RHC ones are harbor entrances.

![image](https://github.com/nkiesel/YRA-Marks/assets/24494353/b8866d20-d0b8-4d66-af9f-1dd8e0810db9)
