### ISSUE TITLE
MC and link

### ISSUE THREAD

**Issue by cygnyx** [nkiesel/YRA-Marks#12]
In jibeset.net for the South Bay Bridge Series – 2024:
https://www.jibeset.net/racedoc/IC/T006771608/si.pdf?1717989316
has a mark described as:

MC Finish: Finish line between the eastern corner of Pier 48 and Green channel marker FL G
2.5s “PA”. This line defines the entrance to McCovey Cove

I think I found this marker at: 37 46.6474, -122 23.2444
but our route did not finish at this mark. Can you add this to your list?

Also, this link in your README no longer works: http://opencpn.org/ocpn/

**Comment by nkiesel** [comment]
Hi, I cannot find a mark at that location when looking at the NOAA charts / mark information. The closest I can find is "South Beach Harbor South Entrance Light 1" which is a "FL (1) G 2.5s 17.7 ft Night light" but at location "37° 46.7071' N 122° 23.1194' W". Was that the finish mark?

I will fix the README, thanks for finding the broken link!

**Comment by cygnyx** [comment]
That looks like Fl G 2.5s “1”.
I’m not certain about this.
Likely needs a visual.
