### ISSUE TITLE
YRA-K is 0.33 NM Off 

### ISSUE THREAD

**Issue by sergei** [nkiesel/YRA-Marks#3]
Javelin sailed Leukemia Cup 10/22/2017. We discovered YRA-K be about 0.33 NM NE from the GPX file.
This is more likely location based on Javelin's GPX track:
37 51.1700 N
122 26.5869 W

[lcr-course-6.zip](https://github.com/nkiesel/YRA-Marks/files/1407728/lcr-course-6.zip)

**Comment by nkiesel** [comment]
Thanks for the feedback; updated.  Given that this is a temporary buoy, the position might change again, but better to have something that was right at least once...
