### ISSUE TITLE
YRA-AS1

### ISSUE THREAD

**Issue by rareitmeyer** [nkiesel/YRA-Marks#4]
Thanks for creating and maintaining this.

I've been racing the South Beach Friday Nights, and YRA AS1 is a bit further west than shown here. EG, the description in the SBYC SIs (http://www.regattanetwork.com/clubmgmt/regatta_uploads/16309/2018FridayNightRaceSeriesSailingInstructions.pdf page 6/7) has the mark at 0.25 nmi E of BVBC, not 0.5 nmi.

I suggest 37.771219,-122.383257, obtained from google maps satellite view at max zoom:

https://www.google.com/maps/place/37%C2%B046'16.4%22N+122%C2%B022'59.7%22W/@37.771219,-122.3833938,31m/data=!3m1!1e3!4m5!3m4!1s0x0:0x0!8m2!3d37.771219!4d-122.383257

**Comment by nkiesel** [comment]
thanks, applied.
