### ISSUE TITLE
Add San Bruno Shoal #1 (for 2018 YRA Summer Series #3)

### ISSUE THREAD

**Issue by rareitmeyer** [nkiesel/YRA-Marks#5]
Again, thanks for creating and maintaining this.

Please add San Bruno Shoal #1, USCG light 4945 (for the 2018-07-14 Summer Series Race).

It's at 37°41.7453', -122°20.3659' per NOAA chart, 37-41-44.719N 122-20-21.954W on the 2018 v6 light list.

Description in the YRA Summer Series SIs (https://www.jibeset.net/show.php?RR=YRA_T003424907&DOC=X3&TYP=pdf) is "San Bruno Shoal Channel 1 (G fl 4.0s)"

**Comment by nkiesel** [comment]
Done
