### ISSUE TITLE
YRA-NG7 [5550] vs G9?

### ISSUE THREAD

**Issue by saleech** [nkiesel/YRA-Marks#7]
Lovely Repository! Thank you for all your hard work!! 

I was trying to clarify in my mind between YRA-NG7 and YRA-G7, and was looking up both marks in the LightList, when I found that your listing for 5550 actually refers to G9 (which should be [5540]?). 
Would you please set me straight as to which is which?

for ref, from your YRA-Marks/San_Francisco.csv file 
"37-56-10.226N","122-29-28.907W","YRA-NG7","[5550] G '9' Fl G 2.5s Corte Madera Channel Light 9"

and from LightList_V6_2018.pdf :
5550 - LIGHT 9 - 37-56-10.228N - 122-29-28.906W

Is there even a YRA-NG9?
Many Thanks from the East Coast!!
- Suzy Leech
http://leechline.com

**Comment by nkiesel** [comment]
Thanks!
Yes, this was clearly a bug, `YRA-NG7` is `[5540]`.  Fixed and pushed
